blank_issues_enabled: false

contact_links:
  - name: Enhancement Request
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=feature-request
    about: Suggest a new feature or other improvement
  - name: Bug Report
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report
    about: Report a bug
  - name: Free Form
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=other
    about: Open a Free Form Issue
  - name: Need help?
    url: https://github.com/noah-nuebling/mac-mouse-fix/discussions
    about: Start a Discussion
