blank_issues_enabled: false

contact_links:
  - name: Feature Request
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=feature-request
    about: Suggest a new feature or other improvement
  - name: Bug Report
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report
    about: Report a bug
  - name: Other
    url: https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=other
    about: Open an issue about another topic
